config/routes.rb
Rails.application.routes.draw do

  def not_implemented
    -> (env) { [501, {}, []] }
  end

  get '/' => redirect('/en')
  resource :beta_opt_out, only: [:create], path: 'opt-out'

  scope '/:locale', locale: /en|cy/ do
    root 'home#show'

    if Feature.active?(:registration)
      devise_for :users, only: [:registrations],
                 controllers:  { registrations: 'registrations' }
    else
      scope '/users' do
        match '/sign_up', to: not_implemented, via: 'get', as: 'new_user_registration'
        match '/edit', to: not_implemented, via: 'get', as: 'edit_user_registration'
      end
    end

    if Feature.active?(:sign_in)
      devise_for :users, only: [:sessions, :passwords],
                         controllers: { sessions: 'sessions' }
      scope '/users' do
        match '/password/new', to: not_implemented, as: 'new_password', via: 'get'
      end
    else
      scope '/users' do
        match '/sign_in', to: not_implemented, via: 'get', as: 'new_user_session'
        match '/sign_out', to: not_implemented, via: 'delete', as: 'destroy_user_session'
      end
    end

    Feature.with(:pensions_calculator) do
      mount PensionsCalculator::Engine => '/tools/:tool_id',
            constraints: ToolMountPoint.for(:pensions_calculator)
    end

    match '/tools/:id', to: not_implemented, via: 'get', as: 'tool'

    resources :action_plans, only: 'show'
    resources :articles,
              only:        'show',
              constraints: ValidResource.new(:article) do
                resource :feedback, only: [:new, :create], controller: :article_feedbacks
              end
    resources :categories, only: 'show',
              constraints:       ValidResource.new(:category)
    resources :search_results, only: 'index', path: 'search'
    resources :news, only: [:show, :index]
    resource :advice, only: :show

    get 'campaigns/revealed-the-true-cost-of-buying-a-car', to: 'car_campaigns#show'
    get 'campaigns/edrychwch-cost-gwirioneddol-prynu-car', to: 'car_campaigns#show'

    resources :static_pages,
              path:        'static',
              only:        'show',
              constraints: ValidResource.new(:static_page)

    resource :feedback, only: [:new, :create], controller: :technical_feedbacks

    resource :cookie_notice_acceptance, only: :create, path: 'cookie-notice'

    resource :newsletter_subscription, only: :create, path: 'newsletter-subscription'

    resource :styleguide,
             controller:  'styleguide',
             only:        'show',
             constraints: { locale: I18n.default_locale } do
      member do

        scope 'components' do
          get 'components_common', path: '/common'
          get 'components_website', path: '/website'
        end

        get 'forms'
        get 'layouts'
        get 'html'
        get 'javascript'

        scope 'pages' do
          get 'pages', path: '/'
          get 'pages_guide', path: '/guide'
          get 'pages_feedback_information', path: '/feedback_information'
          get 'pages_feedback_technical', path: '/feedback_technical'
          get 'pages_feedback_advice', path: '/feedback_advice'
          get 'pages_error', path: '/error'
          get 'pages_news_article', path: '/news_article'
          get 'pages_action_plan', path: '/action_plan'
          get 'pages_news_index', path: '/news_index'
          get 'pages_home', path: '/home'
          get 'pages_search_results', path: '/search_results'
          get 'pages_parent_category_page', path: '/parent_category_page'
          get 'pages_child_category_page', path: '/child_category_page'
          get 'pages_contact', path: '/contact'
        end

        scope 'css' do
          get 'css_overview', path: '/'
          get 'css_basic', path: '/typography'
          get 'css_article_demo', path: '/article-demo'
          get 'css_default_styles', path: '/default-styles'
        end

      end
    end
  end

  match '*path', via: :all, to: not_implemented

end

app/views/shared/_authentication.html.erb
<ul class="authentication <% unless display_search_box_in_header? %>l-authentication<% end %>">
  <% if user_signed_in? %>
    <li class="authentication__item">
      <%= button_to t('authentication.sign_out'), main_app.destroy_user_session_path,
                    class: 'authentication__link', method: :delete %>
    </li>
    <li class="authentication__item">
      <%= link_to t('authentication.my_account'), main_app.edit_user_registration_path,
                  class: 'authentication__link' %>
    </li>
  <% else %>
    <li class="authentication__item">
      <%= link_to t('authentication.sign_in'), main_app.new_user_session_path,
                  class: 'authentication__link' %>
    </li>
    <li class="authentication__item">
      <%= link_to t('authentication.register'), main_app.new_user_registration_path,
                  class: 'authentication__link' %>
    </li>
  <% end %>
</ul>

app/views/shared/_breadcrumbs.html.erb
<nav class="breadcrumbs" role="navigation" aria-label="<%= t('breadcrumbs.aria_label') %>">
  <ul class="unstyled-list">
    <% breadcrumbs.each_with_index do |breadcrumb, index| %>
      <li class="breadcrumbs__item" itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
        <% if index > 0 %>
          <span class="visually-hidden">&gt;</span>
          <span class="breadcrumbs__divider" aria-hidden="true"></span>
        <% end %>
        <%= link_to breadcrumb.path, itemprop: 'url' do %>
          <span itemprop="title"><%= breadcrumb.title %></span>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_call_us.erb
<div class="call-us">
  <%= heading_tag t('contact.call_us'), level: 2, class: 'call-us__title' %>

  <a href="<%= t('contact.telephone_number_href') %>" class="call-us__number"><%= t('contact.telephone_number') %></a>

  <p class="call-us__opening_hours">
    <%= t('contact.opening_hours_html') %>
  </p>

  <p><%= t('contact.call_charges_html') %></p>
</div>

app/views/shared/_call_us.html.erb
<div class="call-us">
  <%= heading_tag t('contact.call_us'), level: 2, class: 'call-us__title' %>

  <a href="<%= t('contact.telephone_number_href') %>" class="call-us__number">
    <%= t('contact.telephone_number') %>
  </a>

  <p class="call-us__opening_hours">
    <%= t('contact.opening_hours_html') %>
  </p>

  <p>
    <%= t('contact.call_charges_html') %>
  </p>
</div>

app/views/shared/_contact_panels.html.erb
<div class="l-constrained">
  <div class="l-contact-panels t-contact-panels">

    <div class="l-contact-panel">
      <div class="contact-panel contact-panel__chat-<%= chat_opening_hours.status %> t-chat" id="js-chat">
        <%= heading_tag level: 2, class: 'contact-panel__heading' do %>
          <span class="icon icon--web-chat"></span><%= t('contact_panels.chat.title') %>
        <% end %>

        <p class="contact-panel__chat-javascript t-chat-javascript">
          <%= t('contact_panels.chat.javascript.description_html') %>
        </p>

        <div class="contact-panel__dynamic-content is-loading" id="js-chat-content">
          <div class="contact-panel__preloader"></div>

          <p class="contact-panel__chat-description t-chat-description" id="js-chat-description">
            <%= chat_opening_hours.description %>
            <%= '*' if translation?('contact_panels.chat.smallprint') %>
          </p>

          <div class="contact-panel__button-container" id="js-chat-cta">
            <div class="contact-panel__button button is-disabled t-chat-button">
              <%= chat_opening_hours.call_to_action %>
            </div>
          </div>
        </div>

        <ul class="t-chat-opening-times contact-panel__list unstyled-list">
          <% chat_opening_hours.periods.each do |period| %>
            <li class="contact-panel__additional-info"><%= period %></li>
          <% end %>
        </ul>

        <% if translation?('contact_panels.chat.smallprint') %>
          <p class="smallprint t-welsh-smallprint">* <%= t('contact_panels.chat.smallprint') %></p>
        <% end %>
      </div>
    </div>

    <div class="contact-panel__border"></div>

    <div class="l-contact-panel">
      <div class="contact-panel">
        <%= heading_tag level: 2, class: 'contact-panel__heading t-contact-heading' do %>
          <span class="icon icon--call-us"></span><%= t('contact_panels.call_us.title') %>
        <% end %>

        <p class="t-contact-introduction"><%= t('contact_panels.call_us.description') %></p>

        <p>
          <a class="contact-panel__telephone t-contact-number" href="<%= t('contact.telephone_number_href') %>">
            <%= t('contact.telephone_number') %></a>
        </p>

        <%= t('contact_panels.call_us.opening_times_html') %>

        <p class="smallprint">* <%= t('contact_panels.call_us.smallprint') %></p>
      </div>
    </div>

    <div class="contact-panel__border"></div>

    <div class="l-contact-panel">
      <div class="contact-panel contact-panel--last t-footer-social-links">
        <%= heading_tag level: 2, class: 'contact-panel__heading' do %>
          <span class="icon icon--sharing"></span><%= t('contact_panels.sharing.title') %>
        <% end %>

        <p><%= t('contact_panels.sharing.description') %></p>

        <div class="contact-panel__button-container">
          <a class="button contact-panel__button contact-panel__button--sharing t-twitter-link" lang="en" href="https://twitter.com/YourMoneyAdvice">
            <span class="icon icon--twitter"></span>
            <span class="visually-hidden">Twitter</span>
          </a>

          <a class="button contact-panel__button contact-panel__button--sharing t-facebook-link" lang="en" href="https://www.facebook.com/MoneyAdviceService?ref=mas">
            <span class="icon icon--facebook"></span>
            <span class="visually-hidden">Facebook</span>
          </a>

          <a class="button contact-panel__button contact-panel__button--sharing t-youtube-link" lang="en" href="https://www.youtube.com/user/MoneyAdviceService">
            <span class="icon icon--youtube"></span>
            <span class="visually-hidden">YouTube</span>
          </a>
        </div>

        <p class="contact-panel__additional-info"><%= t('contact_panels.sharing.more_info_html') %></p>
      </div>
    </div>

  </div>
</div>

<%= content_for :javascripts do %>
  <script type='text/javascript' src='https://webchat.moneyadviceservice.org.uk/include.js?domain=<%= ENV['WEBCHAT_DOMAIN'] %>'></script>
  <script type='text/javascript'>
    sWOProtocol = 'https:';

    sWOImageLoaded = function() {

      <% if chat_opening_hours.open? %>

      var chatCTA = document.getElementById('js-chat-cta'),
          chatDescription = document.getElementById('js-chat-description'),
          chatContent = document.getElementById('js-chat-content');

      if (sWOImage.width == 1) {

        var sWOChatElement = document.createElement('div');
        var sWOChatElementText = document.createTextNode("<%= t('contact_panels.chat.busy.call_to_action') %>");

        sWOChatElement.className = "contact-panel__button button is-disabled t-chat-button";
        sWOChatElement.appendChild(sWOChatElementText);

        chatCTA.innerHTML = "";
        chatCTA.appendChild(sWOChatElement);
        chatDescription.innerHTML = "<%= t('contact_panels.chat.busy.description') %>";

        <% if translation?('contact_panels.chat.smallprint') %>
        chatDescription.innerHTML += '&nbsp;*';
        <% end %>

        chatContent.className = "contact-panel__dynamic-content is-loaded";

      } else {

        var sWOChatElement = document.createElement('a');
        var sWOChatElementText = document.createTextNode("<%= t('contact_panels.chat.available.call_to_action') %>");
        sWOChatElement.className = "contact-panel__button button t-chat-button";
        sWOChatElement.appendChild(sWOChatElementText);

        chatCTA.innerHTML = "";
        chatCTA.appendChild(sWOChatElement);
        chatDescription.innerHTML = "<%= t('contact_panels.chat.available.description') %>";
        chatContent.className = "contact-panel__dynamic-content is-loaded";

        <% if translation?('contact_panels.chat.smallprint') %>
        chatDescription.innerHTML += '&nbsp;*';
        <% end %>

        sWOChatElement.onclick = function() {
          window.open(sWOChatElement.href, "Chat", "width=484,height=361,scrollbars=yes,resizable=yes");
          return false;
        };

        sWOChatElement.href = sWOChatstart;
        sWOChatElement.target = "_blank";

      }

      <% end %>

    };

    if (typeof sWOTrackPage == 'function') {
      sWOTrackPage();

      <%# Track page enagagement (a visit lasting more than 30 seconds) %>
      setTimeout("sWOInvite='';sWOResponse='N';sWOPage=(sWOPage || '')+'%3Ftimer%3Dtrue';sWOTrackPage();", 30000);
    }

  </script>
<% end %>

app/views/shared/_directory.html.erb
<div class="directory l-directory">
  <section class="l-constrained">
    <% items.each do |item| %>
      <div class="directory__item">
        <%= heading_tag(level: 2, class: 'directory__title') do %>
          <%= link_to item.title, item.path %>
        <% end %>

        <p class="directory__description"><%= item.description %></p>
      </div>
    <% end %>
  </section>
</div>

app/views/shared/_feedback_panel.html.erb
<section class="panel feedback-panel">
  <h2 class="feedback-panel__title"><%= t('feedback_panel.title') %></h2>

  <p><%= t('feedback_panel.greeting') %></p>

  <ul>
    <li>
      <%= link_to t('feedback_panel.article_feedback_link_text'), new_article_feedback_path(article.object.id), class: 't-feedback-panel__article-feedback-link' %>
    </li>
    <li>
      <%= link_to t('feedback_panel.technical_feedback_link_text'), new_feedback_path, class: 't-feedback-panel__technical-feedback-link' %>
    </li>
    <li>
      <%= link_to t('feedback_panel.advice_link_text'), advice_path, class: 't-feedback-panel__advice-link' %>
    </li>
  </ul>
</section>

app/views/shared/_footer_primary.html.erb
<div class="l-footer-primary t-footer-primary">
  <div class="l-constrained">
    <div class="l-footer-primary__left">
      <%= render 'shared/newsletter_signup' %>
    </div>

    <div class="l-footer-primary__right">
      <nav role="navigation" aria-label="footer">
        <ul class="l-footer-primary__list l-footer-primary__list--left">
          <li class="footer-primary__list-item">
            <a href="<%= t('footer.about_us_link') %>"><%= t('footer.about_us') %></a>
          </li>

          <li class="footer-primary__list-item">
            <a href="<%= t('footer.our_debt_work_link') %>"><%= t('footer.our_debt_work') %></a>
          </li>

          <li class="footer-primary__list-item">
            <a href="<%= t('footer.media_centre_link') %>"><%= t('footer.media_centre') %></a>
          </li>

          <li class="footer-primary__list-item t-partners-link">
            <a href="<%= t('footer.partners_link') %>"><%= t('footer.partners') %></a>
          </li>

          <li class="footer-primary__list-item">
            <a href="<%= t('footer.jobs_link') %>"><%= t('footer.jobs') %></a>
          </li>
        </ul>

        <ul class="l-footer-primary__list l-footer-primary__list--right">
          <li class="footer-primary__list-item">
            <a href="<%= t('footer.tools_and_resources_link') %>"><%= t('footer.tools_and_resources') %></a>
          </li>

          <li class="footer-primary__list-item">
            <a href="<%= t('footer.news_link') %>"><%= t('footer.news') %></a>
          </li>

          <li class="footer-primary__list-item">
            <a href="<%= t('footer.contact_us_link') %>"><%= t('footer.contact_us') %></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_footer_secondary.html.erb
<div class="l-footer-secondary t-footer-secondary">
  <div class="l-constrained">

    <div class="l-footer-secondary__list--left">
      <ul class="footer-secondary__list">
        <li class="footer-secondary__list-item language-link">
          <% if content_for?(:alternate_link) %>
            <%= yield(:alternate_link) %>
          <% else %>
            <% locals.each do |locale| %>
              <%= link_to({ locale: locale }, { id: "#{locale}Link", lang: locale, :class => 'footer-secondary__link' }) do %>
                <span class="icon icon--globe"></span><%= t("locales.#{locale}") %>
              <% end %>
            <% end %>
          <% end %>
        </li>

        <li class="footer-secondary__list-item accessibility-feedback-link">
          <a class="footer-secondary__link" href="http://accessin.org/usersubmit_mas.php?param=nojscript"
             onclick="window.open('http://accessin.org/usersubmit_mas.php?param=' + window.location,'',
                 'resizable=yes,location=no,scrollbars=yes,toolbar=no,left=20,top=0,height=900,width=800');
                 return false;" title="<%= t('footer_secondary.link_title') %>"
             target="_blank">
            <span class="icon icon--accessibility"></span><%= t('footer_secondary.title') %>
            <span class="visually-hidden"><%= t('footer_secondary.hidden_accessibility') %></span>
          </a>
        </li>
      </ul>
    </div>

    <div class="l-footer-secondary__list--right">
      <ul class="footer-secondary__list">
        <% if display_opt_out_link_in_footer? %>
          <li class="footer-secondary__list-item">
            <%= form_tag(main_app.beta_opt_out_path) do %>
              <input type="hidden" name="redirection_page" value="<%= request.original_url %>">
              <%= button_tag(class: 'footer-secondary__opt-out footer-secondary__link t-opt-out-button') do %>
                <%= t('opt_out.title') %>
              <% end %>
            <% end %>
          </li>
        <% end %>
        <li class="footer-secondary__list-item">
          <a class="footer-secondary__link" href="<%= t('footer.terms_and_conditions_link') %>"><%= t('footer.terms_and_conditions') %></a>
        </li>

        <li class="footer-secondary__list-item">
          <a class="footer-secondary__link" href="<%= t('footer.privacy_statement_link') %>"><%= t('footer.privacy_statement') %></a>
        </li>

        <li class="footer-secondary__list-item">
          <a class="footer-secondary__link" href="<%= t('footer.accessibility_link') %>"><%= t('footer.accessibility') %></a>
        </li>

        <li class="footer-secondary__list-item">
          <a class="footer-secondary__link" href="<%= t('footer.cookie_guide_link') %>"><%= t('footer.cookie_guide') %></a>
        </li>

        <li class="footer-secondary__list-item">
          <a class="footer-secondary__link" href="<%= t('footer.site_map_link') %>"><%= t('footer.site_map') %></a>
        </li>

      </ul>
    </div>
  </div>
</div>

<% if cookies_not_accepted? %>
  <div class="cookie-message">
    <div class="l-constrained">
      <%= form_tag main_app.cookie_notice_acceptance_path, remote: true, authenticity_token: true, class: 'js-cookie-message' do %>
        <p class="cookie-message__content"><%= t('footer.cookie_message.body_html', url: t('footer.cookie_guide_link')) %></p>
        <button class="cookie-message__close-button">
          <span class="visually-hidden"><%= t('footer.cookie_message.close_button') %></span><span class="icon icon--close"></span>
        </button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_mobile_nav.html.erb
<ul class="mobile-nav">
  <% if display_menu_button_in_header? %>
    <li class="mobile-nav__item">
      <a class="mobile-nav__link mobile-nav__link--menu" href="#primary-nav"><%= t('mobile_nav.menu') %></a>
    </li>
  <% end %>
  <% if display_search_box_in_header? %>
    <li class="mobile-nav__item mobile-nav__item--search">
      <a class="mobile-nav__link mobile-nav__link--search" href="#search-bar">
        <span class="icon icon--search-white"></span>
        <span class="visually-hidden"><%= t('mobile_nav.search') %></span>
      </a>
    </li>
  <% end %>
</ul>

app/views/shared/_nav.html.erb
<% active_categories = [] unless (defined?(:active_categories) && active_categories.present?) %>

<a href="#top" class="link-to-top-block"><%= t('back_to_top') %>
  <span class="icon icon--up-chevron-blue"></span>
</a>

<% if categories.present? %>
  <nav class="nav" role="navigation" aria-label="main" id="primary-nav" tabindex="-1">
    <ul class="link-list-primary">
      <% categories.each do |category| %>
        <% if active_categories.member?(category.id) %>
          <li class="link-list-primary__item link-list-primary__item--selected">

            <% if child_selected = category.contents && category.contents.any? { |c| active_categories.include?(c.id) } %>
              <%= link_to category.title, category.path, class: "link-list-primary__text" %>
            <% else %>
              <span class="link-list-primary__text is-selected"><%= category.title %></span>
            <% end %>

            <ul class="link-list-secondary">
              <% category.contents.each do |sub_category| %>
                <li class="link-list-secondary__item">
                  <%= link_to sub_category.title, sub_category.path,
                              class: "link-list-secondary__text #{active_categories.member?(sub_category.id) ? 'is-selected' : ''}"
                  %>
                </li>
              <% end %>
            </ul>

          </li>
        <% else %>
          <li class="link-list-primary__item">
            <%= link_to category.title, category.path, class: 'link-list-primary__text' %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </nav>
<% end %>

app/views/shared/_newsletter_signup.html.erb
<%= form_tag(main_app.newsletter_subscription_path, class: 'newsletter-signup t-newsletter', remote: true) do %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

  <%= heading_tag t('newsletter_subscriptions.title'), level: 2, class: 'newsletter-signup__heading' %>

  <ul class="newsletter-signup__benefits-list list-benefits">
    <% t('newsletter_subscriptions.benefits').each do |benefit| %>
      <li><%= benefit %></li>
    <% end %>
  </ul>

  <fieldset class="newsletter-signup__form js-newsletter-form">
    <legend class="visually-hidden"><%= t('newsletter_subscriptions.hidden_title') %></legend>
    <%= label_tag('subscription[email]', t('newsletter_subscriptions.label'), class: 'newsletter-signup__label') %>
    <%= text_field_tag('subscription[email]', nil, class: 't-newsletter-email js-newsletter-input newsletter-signup__input') %>
    <%= button_tag(t('newsletter_subscriptions.button'), type: 'submit', class: 't-newsletter-button button newsletter-signup__button') %>
  </fieldset>
<% end %>

app/views/shared/_promo.html.erb
<div class="l-constrained">
  <section class="clearfix l-padded">
    <% items.each do |item| %>
      <div class="promo l-homepage-promo">
        <h2 class="promo__heading">
          <%= link_to item['url'] do %>
            <%= image_tag("promos/#{item['image']}", alt: '') %>
            <%= item['text'] %>
          <% end %>
        </h2>

        <p class="promo__content"><%= item['content'] %></p>
      </div>
    <% end %>
  </section>
</div>

app/views/shared/_trust_banner.html.erb
<div class="l-constrained">
  <div class="trust-banner l-trust-banner">
    <p class="trust-banner__heading"><%= t('home.show.heading') %></p>
  </div>
</div>